controller_manager:
  ros__parameters:
    update_rate: 10
    use_sim_time: false

    diff_cont:
      type: diff_drive_controller/DiffDriveController 

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster   

    imu_broad:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 40.0

    base_frame_id: base_link

    left_wheel_names: ["left_front_wheel_joint"]
    right_wheel_names: ["right_front_wheel_joint"]
    wheel_separation: 0.6223
    wheel_radius: 0.10115

    # use_twist_stamped: false
    use_stamped_vel: false
    # open_loop: false    

    # wheels_per_side: 2
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

# joint_broad:
#   ros__parameters:
#     use_local_topics: true

# imu_broad:

