controller_manager:
  ros__parameters:
    update_rate: 60
    use_sim_time: false

    diff_cont:
      type: diff_drive_controller/DiffDriveController 

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster   

    imu_broad:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster
    
    right_range_broad:
      type: range_sensor_broadcaster/RangeSensorBroadcaster
    
    left_range_broad:
      type: range_sensor_broadcaster/RangeSensorBroadcaster

diff_cont:
  ros__parameters:
    left_wheel_names: ["left_front_wheel_joint"]
    right_wheel_names: ["right_front_wheel_joint"]

    wheel_separation: 0.6223 #meters
    wheel_radius: 0.10115 #meters
    wheels_per_side: 1 #default

    wheel_separation_multiplier: 1.0 #default
    left_wheel_radius_multiplier: 1.0 #default
    right_wheel_radius_multiplier: 1.0 #default

    publish_rate: 60.0 #Hz
    odom_frame_id: odom
    base_frame_id: base_link 
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] #default
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] #default
    
    position_feedback: true 
    open_loop: false 
    enable_odom_tf: false 
    use_stamped_vel: false
    cmd_vel_timeout: 0.5 
    publish_limited_velocity: false
    # velocity_rolling_window_size: 10 #default

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 400.0
    linear.x.min_velocity: -400.0
    # linear.x.max_acceleration: 0.0
    # linear.x.min_acceleration: 0.0
    # linear.x.max_jerk: 0.0
    # linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 400.0
    angular.z.min_velocity: -400.0
    # angular.z.max_acceleration: 0.0
    # angular.z.min_acceleration: 0.0
    # angular.z.max_jerk: 0.0
    # angular.z.min_jerk: 0.0

joint_broad:
  ros__parameters:
    use_local_topics: false

imu_broad:
  ros__parameters:
    sensor_name: imu
    frame_id: imu_link
    # update covariances depending on the imu initial readings
    # static_covariance_orientation:
    # static_covariance_angular_velocity:
    # static_covariance_linear_acceleration:

right_range_broad:
  ros__parameters:
    sensor_name: right_range
    frame_id: right_range_link
    radiation_type: 0
    field_of_view: 0.52 #default
    min_range: 0.0 #default
    max_range: 0.4 #default

left_range_broad:
  ros__parameters:
    sensor_name: left_range
    frame_id: left_range_link
    radiation_type: 0
    field_of_view: 0.52 #default
    min_range: 0.0 #default
    max_range: 0.4 #default

