twist_mux:
  ros__parameters:
    use_stamped: False
    topics:
      smoothed:
        topic: cmd_vel_nvs
        timeout: 0.1
        priority: 20
      navigation:
        topic: cmd_vel
        timeout: 0.10
        priority: 10
      joystick:
        topic: cmd_vel_joy
        timeout: 0.1
        priority: 100
      keyboard:
        topic: cmd_vel_key
        timeout: 0.1
        priority: 100