# Form implementation generated from reading ui file 'sample_bot_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(420, 300)
        self.title_lbl = QtWidgets.QLabel(parent=Form)
        self.title_lbl.setGeometry(QtCore.QRect(130, 10, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.title_lbl.setFont(font)
        self.title_lbl.setObjectName("title_lbl")
        self.base_bt = QtWidgets.QPushButton(parent=Form)
        self.base_bt.setGeometry(QtCore.QRect(10, 80, 71, 61))
        self.base_bt.setObjectName("base_bt")
        self.dest1_bt = QtWidgets.QPushButton(parent=Form)
        self.dest1_bt.setGeometry(QtCore.QRect(100, 80, 71, 61))
        self.dest1_bt.setObjectName("dest1_bt")
        self.dest2_bt = QtWidgets.QPushButton(parent=Form)
        self.dest2_bt.setGeometry(QtCore.QRect(200, 80, 71, 61))
        self.dest2_bt.setObjectName("dest2_bt")
        self.dest3_bt = QtWidgets.QPushButton(parent=Form)
        self.dest3_bt.setGeometry(QtCore.QRect(10, 180, 71, 61))
        self.dest3_bt.setObjectName("dest3_bt")
        self.dest4_bt = QtWidgets.QPushButton(parent=Form)
        self.dest4_bt.setGeometry(QtCore.QRect(100, 180, 71, 61))
        self.dest4_bt.setObjectName("dest4_bt")
        self.dest5_bt = QtWidgets.QPushButton(parent=Form)
        self.dest5_bt.setGeometry(QtCore.QRect(200, 180, 71, 61))
        self.dest5_bt.setObjectName("dest5_bt")
        self.x_pos_in = QtWidgets.QLineEdit(parent=Form)
        self.x_pos_in.setGeometry(QtCore.QRect(290, 90, 113, 21))
        self.x_pos_in.setObjectName("x_pos_in")
        self.x_pos_lbl = QtWidgets.QLabel(parent=Form)
        self.x_pos_lbl.setGeometry(QtCore.QRect(290, 70, 61, 16))
        self.x_pos_lbl.setObjectName("x_pos_lbl")
        self.x_pos_out = QtWidgets.QLineEdit(parent=Form)
        self.x_pos_out.setGeometry(QtCore.QRect(290, 130, 113, 21))
        self.x_pos_out.setObjectName("x_pos_out")
        self.y_pos_label = QtWidgets.QLabel(parent=Form)
        self.y_pos_label.setGeometry(QtCore.QRect(290, 110, 61, 16))
        self.y_pos_label.setObjectName("y_pos_label")
        self.angle_out = QtWidgets.QLineEdit(parent=Form)
        self.angle_out.setGeometry(QtCore.QRect(290, 180, 113, 21))
        self.angle_out.setObjectName("angle_out")
        self.angle_lbl = QtWidgets.QLabel(parent=Form)
        self.angle_lbl.setGeometry(QtCore.QRect(290, 160, 61, 16))
        self.angle_lbl.setObjectName("angle_lbl")
        self.pos_bt = QtWidgets.QPushButton(parent=Form)
        self.pos_bt.setGeometry(QtCore.QRect(290, 210, 111, 31))
        self.pos_bt.setObjectName("pos_bt")
        self.response_lbl = QtWidgets.QLabel(parent=Form)
        self.response_lbl.setGeometry(QtCore.QRect(10, 269, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.response_lbl.setFont(font)
        self.response_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.response_lbl.setObjectName("response_lbl")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title_lbl.setText(_translate("Form", "BOT CONTROLLER"))
        self.base_bt.setText(_translate("Form", "BASE"))
        self.dest1_bt.setText(_translate("Form", "DEST. 1"))
        self.dest2_bt.setText(_translate("Form", "DEST. 2"))
        self.dest3_bt.setText(_translate("Form", "DEST. 3"))
        self.dest4_bt.setText(_translate("Form", "DEST. 4"))
        self.dest5_bt.setText(_translate("Form", "DEST. 5"))
        self.x_pos_lbl.setText(_translate("Form", "x position"))
        self.y_pos_label.setText(_translate("Form", "y position"))
        self.angle_lbl.setText(_translate("Form", "angle"))
        self.pos_bt.setText(_translate("Form", "RUN"))
        self.response_lbl.setText(_translate("Form", "ROBOT RESPONSE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
