# Form implementation generated from reading ui file 'sample_bot_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import numpy as np
import rclpy
rclpy.init(args=None)
from applicate_bot import bot_control
bot = bot_control.BotControl()

# Set waypoints and start navigation
waypoints = {
            '0':(0.0, 0.0, 0.0),  # Assuming the robot stops facing the original direction
            '1':(4.0, 2.5, np.radians(0)),
            '2':(2.5, 2.5, np.radians(90)),
            '3':(2.5, 7.0, np.radians(-130.60)),
            '4':(-3.5, 0.0, np.radians(11.31)),
            '5':(9.0, 2.5, np.radians(155.56)),
            '6':(3.5, 5.0, np.radians(-125.00)),
}

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(420, 300)
        self.title_lbl = QtWidgets.QLabel(parent=Form)
        self.title_lbl.setGeometry(QtCore.QRect(130, 10, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.title_lbl.setFont(font)
        self.title_lbl.setObjectName("title_lbl")
        self.base_bt = QtWidgets.QPushButton(parent=Form)
        self.base_bt.setGeometry(QtCore.QRect(10, 80, 71, 61))
        self.base_bt.setObjectName("base_bt")
        self.dest1_bt = QtWidgets.QPushButton(parent=Form)
        self.dest1_bt.setGeometry(QtCore.QRect(100, 80, 71, 61))
        self.dest1_bt.setObjectName("dest1_bt")
        self.dest2_bt = QtWidgets.QPushButton(parent=Form)
        self.dest2_bt.setGeometry(QtCore.QRect(200, 80, 71, 61))
        self.dest2_bt.setObjectName("dest2_bt")
        self.dest3_bt = QtWidgets.QPushButton(parent=Form)
        self.dest3_bt.setGeometry(QtCore.QRect(10, 180, 71, 61))
        self.dest3_bt.setObjectName("dest3_bt")
        self.dest4_bt = QtWidgets.QPushButton(parent=Form)
        self.dest4_bt.setGeometry(QtCore.QRect(100, 180, 71, 61))
        self.dest4_bt.setObjectName("dest4_bt")
        self.dest5_bt = QtWidgets.QPushButton(parent=Form)
        self.dest5_bt.setGeometry(QtCore.QRect(200, 180, 71, 61))
        self.dest5_bt.setObjectName("dest5_bt")
        self.x_pos_in = QtWidgets.QLineEdit(parent=Form)
        self.x_pos_in.setGeometry(QtCore.QRect(290, 90, 113, 21))
        self.x_pos_in.setObjectName("x_pos_in")
        self.x_pos_lbl = QtWidgets.QLabel(parent=Form)
        self.x_pos_lbl.setGeometry(QtCore.QRect(290, 70, 61, 16))
        self.x_pos_lbl.setObjectName("x_pos_lbl")
        self.y_pos_in = QtWidgets.QLineEdit(parent=Form)
        self.y_pos_in.setGeometry(QtCore.QRect(290, 130, 113, 21))
        self.y_pos_in.setObjectName("y_pos_in")
        self.y_pos_label = QtWidgets.QLabel(parent=Form)
        self.y_pos_label.setGeometry(QtCore.QRect(290, 110, 61, 16))
        self.y_pos_label.setObjectName("y_pos_label")
        self.angle_in = QtWidgets.QLineEdit(parent=Form)
        self.angle_in.setGeometry(QtCore.QRect(290, 180, 113, 21))
        self.angle_in.setObjectName("angle_in")
        self.angle_lbl = QtWidgets.QLabel(parent=Form)
        self.angle_lbl.setGeometry(QtCore.QRect(290, 160, 61, 16))
        self.angle_lbl.setObjectName("angle_lbl")
        self.pos_bt = QtWidgets.QPushButton(parent=Form)
        self.pos_bt.setGeometry(QtCore.QRect(290, 210, 111, 31))
        self.pos_bt.setObjectName("pos_bt")
        self.response_lbl = QtWidgets.QLabel(parent=Form)
        self.response_lbl.setGeometry(QtCore.QRect(10, 269, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.response_lbl.setFont(font)
        self.response_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.response_lbl.setObjectName("response_lbl")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # FUNCTIONS
        self.base_bt.clicked.connect(lambda: self.goDest(["Base Station", 0.0, 0.0, 0.0]))
        self.dest1_bt.clicked.connect(lambda: self.goDest(["Destination 1", 1.0, 0.0, 0.0]))
        self.dest2_bt.clicked.connect(lambda: self.goDest(["Destination 2", 2.0, 2.0, 180.0]))
        self.pos_bt.clicked.connect(lambda: self.goDest(self.getDest()))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title_lbl.setText(_translate("Form", "BOT CONTROLLER"))
        self.base_bt.setText(_translate("Form", "BASE"))
        self.dest1_bt.setText(_translate("Form", "DEST. 1"))
        self.dest2_bt.setText(_translate("Form", "DEST. 2"))
        self.dest3_bt.setText(_translate("Form", "DEST. 3"))
        self.dest4_bt.setText(_translate("Form", "DEST. 4"))
        self.dest5_bt.setText(_translate("Form", "DEST. 5"))
        self.x_pos_lbl.setText(_translate("Form", "x position"))
        self.y_pos_label.setText(_translate("Form", "y position"))
        self.angle_lbl.setText(_translate("Form", "angle"))
        self.pos_bt.setText(_translate("Form", "RUN"))
        self.response_lbl.setText(_translate("Form", "ROBOT RESPONSE"))


    def goDest(self, arr):
        dest = arr[0]
        x = float(arr[1])
        y = float(arr[2])
        a = np.radians(float(arr[3]))
        if dest == "error":
            self.err("wrong input")
        else:
            self.response_lbl.setText("Going to " + dest)
            bot.follow_waypoints([bot.create_pose_stamped(x, y, a)])
    
    def getDest(self):
        x = self.x_pos_in.text()
        y = self.y_pos_in.text()
        a = self.angle_in.text()
        xneg = False
        yneg = False
        aneg = False
        if x[0]== '-':
            x = self.rmchars(x, 1, 'left')
            xneg = True
        if y[0]== '-':
            y = self.rmchars(y, 1, 'left')
            yneg = True
        if a[0]== '-':
            a = self.rmchars(a, 1, 'left')
            aneg = True
        if x.isnumeric() and y.isnumeric() and a.isnumeric():
            if xneg:
                x= '-'+x
            if yneg:
                y='-'+y
            if aneg:
                a='-'+a 
            txt = "pos: " + x + ", " + y + ": " + a + "°" 
            arr = [txt, x, y, a]
            return arr
        else:
            
            return ["error", 0,0,0]
    
    def err(self, msg):
        self.response_lbl.setText("Error: " + msg)
        return
    
    def rmchars(self, word, n, dir):
        new =''
        for i in range(len(word)):
            if dir == 'left' and i < n+i:
                n-=1
                continue
            elif dir == 'right' and i> len(word)-n:
                n-=1
                continue
            new+=word[i]
        return new

def main(args=None):
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
    

if __name__ == "__main__":
    main()