<?xml version="1.0"?>
<!-- ROBOT CORE COMPONENTS-->
 
<!-- call xacro-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <!-- Inertial xacro-->
    <xacro:include filename="inertial_macros.xacro"/>

    <!-- Static Variables -->
    <xacro:property name="left_roll" value="${-pi/2}"/>
    <xacro:property name="right_roll" value="${pi/2}"/>

    <!-- Independent Variables -->
    <xacro:property name="chassis_base" value="0.3"/>
    <xacro:property name="chassis_height" value="0.15"/>
    <xacro:property name="chassis_mass" value="0.36"/>

    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_length" value="0.05"/>
    <xacro:property name="wheel_mass" value="0.1"/>

    <!-- Dependent Variables-->
    <xacro:property name="chassis_joint_offset" value="${-chassis_base/3}"/>
    <xacro:property name="chassis_link_offset" value="${chassis_base/2}"/>
    <xacro:property name="chassis_height_offset" value="${chassis_height/2}"/>
    <xacro:property name="frontwheel_offset" value="${(chassis_base * 0.5/5) - (chassis_joint_offset)}"/>
    <xacro:property name="backwheel_offset" value="${-(chassis_base * 0.5/5)}"/>
    <xacro:property name="leftwheel_offset" value="${(chassis_base/2) + (wheel_length/2)}"/>
    <xacro:property name="rightwheel_offset" value="-${(chassis_base/2) + (wheel_length/2)}"/>

    <!-- Materials -->
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>
    
    <material name="orange">
        <color rgba="1 0.3 1 1" />
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <!-- links -->
    <link name="base">
    </link>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_link_offset} 0 ${chassis_height_offset}"/>
            <geometry>
                <box size="${chassis_base} ${chassis_base} ${chassis_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${chassis_link_offset} 0 ${chassis_height_offset}"/>
            <geometry>
                <box size="${chassis_base} ${chassis_base} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_base}" y="${chassis_base}" z="${chassis_height}">
            <origin xyz="${chassis_link_offset} 0 ${chassis_height_offset}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <link name="left_back_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link> 

    <link name="right_back_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link> 

    <link name="left_front_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link> 

    <link name="right_front_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link> 

    <!-- Joints -->
    <joint name="chassis-base" type="fixed">
        <parent link="base"/>
        <child link="chassis"/>
        <origin xyz="${chassis_joint_offset} 0 0"/>
    </joint>

    <joint name="left_back_wheel-base" type="continuous">
        <parent link="base"/>
        <child link="left_back_wheel"/>
        <origin xyz="${backwheel_offset} ${leftwheel_offset} 0" rpy="${left_roll} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>
    
    <joint name="right_back_wheel-base" type="continuous">
        <parent link="base"/>
        <child link="right_back_wheel"/>
        <origin xyz="${backwheel_offset} ${rightwheel_offset} 0" rpy="${right_roll} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <joint name="left_front_wheel-base" type="continuous">
        <parent link="base"/>
        <child link="left_front_wheel"/>
        <origin xyz="${frontwheel_offset} ${leftwheel_offset} 0" rpy="${left_roll} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>
    
    <joint name="right_front_wheel-base" type="continuous">
        <parent link="base"/>
        <child link="right_front_wheel"/>
        <origin xyz="${frontwheel_offset} ${rightwheel_offset} 0" rpy="${right_roll} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>
</robot>