<?xml version="1.0"?>
<!-- 
ROBOT PROPERTIES 

Lengths are in meters, Mass are in kilograms, Angles are in radians, Values are type double.
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- Constants -->
    <xacro:property name="left_roll" value="${-pi/2}"/>
    <xacro:property name="right_roll" value="${pi/2}"/>

    <!-- Variables -->
    <xacro:property name="scale_val" value="1.0"/>
    <xacro:property name="scale" value="${scale_val} ${scale_val} ${scale_val}"/>

    <xacro:property name="bot_pos_x" value="0.0"/>
    <xacro:property name="bot_pos_y" value="0.0"/>
    <xacro:property name="bot_pos_z" value="-0.019"/>

    <xacro:property name="actual_bot_width" value="0.25"/>
    <xacro:property name="actual_bot_length" value="0.15"/>

    <xacro:property name="actual_chassis_height" value="0.067"/>
    <xacro:property name="chassis_mass" value="10.0"/>

    <xacro:property name="actual_storage_height" value="1.0"/>
    <xacro:property name="storage_mass" value="10.0"/>

    <xacro:property name="actual_top_height" value="1.0"/>
    <xacro:property name="top_mass" value="10.0"/>

    <xacro:property name="actual_wheel_radius" value="0.1275"/>
    <xacro:property name="actual_wheel_thickness" value="0.1"/>
    <xacro:property name="actual_shaft_length" value="0.2"/>
    <xacro:property name="total_wheel_length" value="${actual_shaft_length + actual_wheel_thickness}"/>
    <xacro:property name="wheel_mass" value="5.0"/>

    <!-- Macros-->
    <xacro:macro name="scaled_origin" params="x y z">
        <origin xyz="   ${bot_pos_x + (x * scale_val)}
                        ${bot_pos_y + (y * scale_val)} 
                        ${bot_pos_z + (z * scale_val)}" />
    </xacro:macro>

    <xacro:macro name="scaled_origin_rpy" params="x y z roll pitch yaw">
        <origin xyz="   ${bot_pos_x + (x * scale_val)} 
                        ${bot_pos_y + (y * scale_val)} 
                        ${bot_pos_z + (z * scale_val)}" 
                
                rpy="${roll} ${pitch} ${yaw}"/>
    </xacro:macro>

    <!-- Materials -->
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>
    
    <material name="orange">
        <color rgba="1 0.3 1 1" />
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- Inertials -->
    <!-- Specify some standard inertial calculations https://en.wikipedia.org/wiki/List_of_moments_of_inertia -->
    <xacro:macro name="inertial_sphere" params="mass radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(2/5) * mass * (radius*radius)}" ixy="0.0" ixz="0.0"
                    iyy="${(2/5) * mass * (radius*radius)}" iyz="0.0"
                    izz="${(2/5) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>  

    <xacro:macro name="inertial_box" params="mass x y z *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * (y*y+z*z)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * (x*x+z*z)}" iyz="0.0"
                    izz="${(1/12) * (x*x+y*y)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="inertial_cylinder" params="mass length radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
                    izz="${(1/2) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>


</robot>