<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Lidar Link -->
    <link name="ldlidar_link">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/> 
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${pi}"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:inertial_cylinder mass="0.10" length="0.04" radius="0.05">
                <xacro:scaled_origin_rpy x="0" y="0"  z="0" roll="0" pitch="0" yaw="0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Lidar Joint to Base Link -->
    <joint name="lidar_link_joint" type="fixed">
        <parent link="base_link"/>
        <child link="ldlidar_link"/>
        <origin xyz="0.0 0.0 ${(scale_val* (actual_chassis_height + actual_storage_height + actual_top_height)) + 0.02 -0.7}" rpy="0.0 0.0 0.0"/>
        <!-- <origin xyz="0.0 0.0 ${(scale_val* (actual_chassis_height) + 0.02)}" rpy="0.0 0.0 0.0"/> -->
    </joint>

    <!-- Macro for IR Sensors -->
    <xacro:macro name="range_link_joint" params="pos_x">
        <link name="${pos_x}_range_link">
            <visual>
                <geometry> 
                    <box size="0.015 0.03 0.001"/>
                </geometry>
                <xacro:scaled_origin_rpy x="0.0" y="0.0"  z="0.0" roll="0" pitch="0" yaw="0"/>
            </visual>
            <collision>
                <geometry> 
                    <box size="0.015 0.03 0.01"/>
                </geometry>
                <xacro:scaled_origin_rpy x="0.0" y="0.0"  z="0.0" roll="0" pitch="0" yaw="0"/>
            </collision>
            <xacro:inertial_box mass="0.001" x="0.0" y="0.0" z="0.0">
            <origin xyz="0.0 0 0.0" rpy="-1 0 0"/>
            </xacro:inertial_box>
        </link> 

        <xacro:if value="${pos_x == 'left'}">
            <xacro:property name="offset_x" value="${+(actual_bot_width/3)}"/>
        </xacro:if>
        <xacro:if value="${pos_x == 'right'}">
            <xacro:property name="offset_x" value="${-(actual_bot_width/3)}"/>
        </xacro:if>
        <joint name="${pos_x}_range_joint" type="fixed">
            <parent link="base_link"/>
            <child link="${pos_x}_range_link"/>
            <xacro:scaled_origin_rpy x="${(actual_bot_length/2) + smol_offset}" y="${offset_x + 0.02}"  z="${actual_wheel_radius}" roll="0" pitch="0" yaw="0"/>
            <axis xyz="0 0 0"/>
        </joint>

    </xacro:macro>

    <!-- left IR sensor -->
    <xacro:range_link_joint pos_x="left"/>
    <!-- right IR sensor -->
    <xacro:range_link_joint pos_x="right"/>

    <!-- IMU Link -->
    <link name="imu_link">
        <visual>
            <geometry>
                <cylinder radius="0.01" length="0.01"/> 
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${pi}"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.01" length="0.01"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:inertial_cylinder mass="0.10" length="0.01" radius="0.01">
                <xacro:scaled_origin_rpy x="0" y="0"  z="0" roll="0" pitch="0" yaw="0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- IMU joint to base link -->
    <joint name="imu_link_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0.0 0.0 ${scale_val* 0.0}" rpy="0.0 0.0 0.0"/>
    </joint>

    
</robot>